apiVersion: v1
kind: Namespace
metadata:
  name: details
  labels:
    istio-injection: enabled  
---
apiVersion: v1
kind: Namespace                           # Adding namespace resource
metadata:
  name: productpage
  labels:
    istio-injection: enabled 
---
apiVersion: v1
kind: Namespace                           # Adding namespace resource
metadata:
  name: ratings
  labels:
    istio-injection: enabled 
---
apiVersion: v1
kind: Namespace                           # Adding namespace resource
metadata:
  name: reviews
  labels:
    istio-injection: enabled