apiVersion: v1
kind: Service
metadata:
  name: details
  labels:
    app: details
    service: details
  namespace: details                     # Add namespace details
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: details
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: details-vs
  namespace: details                  # Namespace where the details service resides
spec:
  hosts:
  - details            # Replace with the FQDN for details service
  http:
  - route:
    - destination:
        host: details                # Service name within the same namespace
        subset: blue                  # Route traffic to version "v1"
        port:
          number: 9080
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: details-dr
  namespace: details                  # Namespace where the details service resides
spec:
  host: details                      # Service name within the same namespace
  subsets:
  - name: blue
    labels:
      app: details
      color: blue
  - name: green
    labels:
      app: details
      color: green
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN