apiVersion: v1
kind: Service
metadata:
  name: ratings
  labels:
    app: ratings
    service: ratings
  namespace: ratings                  # Add namespace details
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: ratings
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ratings-vs
  namespace: ratings                  # Namespace where the ratings service resides
spec:
  hosts:
  - ratings            # Replace with the FQDN for ratings service
  http:
  - route:
    - destination:
        host: ratings                # Service name within the same namespace
        subset: blue                  # Route traffic to version "v1"
        port:
          number: 9080
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: ratings-dr
  namespace: ratings                  # Namespace where the ratings service resides
spec:
  host: ratings                      # Service name within the same namespace
  subsets:
  - name: blue
    labels:
      app: ratings
      color: blue
  - name: green
    labels:
      app: ratings
      color: green
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
