apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-ratings
  labels:
    account: ratings
  namespace: ratings                  # Add namespace details
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings-blue
  labels:
    app: ratings
    color: blue                      # Label for blue deployment
  namespace: ratings                  # Add namespace details
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratings
      color: blue                    # Selector for blue deployment
  template:
    metadata:
      labels:
        app: ratings
        color: blue                # Label for blue deployment
    spec:
      serviceAccountName: bookinfo-ratings
      containers:
      - name: ratings
        image: docker.io/istio/examples-bookinfo-ratings-v1:1.19.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
