apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-reviews
  labels:
    account: reviews
  namespace: reviews                  # Add namespace details
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-blue
  labels:
    app: reviews
    color: blue                      # Label for blue deployment
  namespace: reviews                  # Add namespace details
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
      color: blue                    # Selector for blue deployment
  template:
    metadata:
      labels:
        app: reviews
        color: blue                # Label for blue deployment
    spec:
      serviceAccountName: bookinfo-reviews
      containers:
      - name: reviews
        image: docker.io/istio/examples-bookinfo-reviews-v2:1.19.1
        imagePullPolicy: IfNotPresent
        env:
        - name: LOG_DIR
          value: "/tmp/logs"
        - name: RATINGS_HOSTNAME
          value: "ratings.ratings.svc.cluster.local"         
        ports:
        - containerPort: 9080
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: wlp-output
          mountPath: /opt/ibm/wlp/output
      volumes:
      - name: wlp-output
        emptyDir: {}
      - name: tmp
        emptyDir: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-green
  labels:
    app: reviews
    color: green                     # Label for green deployment
  namespace: reviews                  # Add namespace details
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
      color: green                   # Selector for green deployment
  template:
    metadata:
      labels:
        app: reviews
        color: green               # Label for green deployment
    spec:
      serviceAccountName: bookinfo-reviews
      containers:
      - name: reviews
        image: docker.io/istio/examples-bookinfo-reviews-v3:1.19.1
        imagePullPolicy: IfNotPresent
        env:
        - name: LOG_DIR
          value: "/tmp/logs"
        - name: RATINGS_HOSTNAME
          value: "ratings.ratings.svc.cluster.local"
        ports:
        - containerPort: 9080
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: wlp-output
          mountPath: /opt/ibm/wlp/output
      volumes:
      - name: wlp-output
        emptyDir: {}
      - name: tmp
        emptyDir: {}
